### ISSUE TITLE
Instructions for inference are untested

### ISSUE THREAD

**Issue by GrantPerkins** [GrantPerkins/CoralSagemaker#3]
I have yet to run through the steps for running inference on a Raspberry Pi, so they may be wrong.

**Comment by cbennet** [comment]
record_video.py runs but does not create an output file at the given path, or anywhere else I can find

**Comment by GrantPerkins** [comment]
Good catch! Should be fixed in latest commit.

**Comment by GrantPerkins** [comment]
@cbennet is this completely tested or should I work on this today?

**Comment by cbennet** [comment]
I didn’t have a hatch or cargo so I couldn’t test the actual inferencing.

**Comment by GrantPerkins** [comment]
My cargo is missing in action so I guess I will cop another

**Comment by GrantPerkins** [comment]
Update: this is half-tested. Have yet to try with our model.
